url: https://nobeas.com
baseurl:

# Site settings
title: Nobeas
email: info@nobeas.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Daniel Karakka
  pic: 1
  position: CEO
  social:
    - title: home
      url: http://karakaz.io
    - title: github
      url: https://github.com/karakaz
    - title: linkedin
      url: https://linkedin.com/in/karakaz

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url:
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/nobeas
  - title: github
    url: http://github.com/nobeas-official

# Postal address (add as many lines as necessary)
address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty